### ISSUE TITLE
Absence of Maximum number of products (INTEGER validation)

### ISSUE THREAD

**Issue by muthugit** [whirldata/aptengine-magento-extension#3]
In admin panel, I can enter the text values in Maximum number of products field.
Reference in attachment.
![screen shot 2016-10-07 at 11 44 28 am](https://cloud.githubusercontent.com/assets/12176352/19180470/aac147fe-8c83-11e6-8a0a-2cc3b2dd1098.png)

**Comment by gauti023** [comment]
This is Magento OOTB feature there is no specific validation for the configuration values.
